const formTranslations = {
  en: {
    form: "Patient Consultation Form",
    reason: "Reason for visit",
    reason_ph: "E.g. Fever since 2 days",
    symptom_cat: "Symptom category",
    symptom_cat_opts: ["General", "Respiratory", "Cardiac", "Gastro", "Other"],
    category_type: "Type",
    category_type_opts: ["Primary", "Recurring", "Chronic", "Other"],
    symptoms: "Symptoms",
    symptoms_ph: "E.g. Headache",
    duration: "Duration",
    duration_opts: ["Hours", "Days", "Weeks"],
    severity: "Severity",
    severity_opts: ["Mild", "Moderate", "Severe"],
    health_history: "Health History",
    diabetes: "Diabetes",
    bp: "BP",
    tb: "TB",
    asthma: "Asthma",
    other: "Other",
    cur_meds: "Current medicines",
    cur_meds_ph: "Yes/No or list names",
    date: "Date",
    date_ph: "YYYY-MM-DD",
    time: "Time",
    time_ph: "HH:MM",
    hosp: "Hospital Type",
    select_hosp: "Select Type",
    private: "Private",
    govt: "Government",
    submit: "SUBMIT",
  },
  pa: {
    form: "ਮਰੀਜ਼ ਸਲਾਹ ਫਾਰਮ",
    reason: "ਮੁਲਾਕਾਤ ਦਾ ਕਾਰਨ",
    reason_ph: "ਉਦਾਹ: 2 ਦਿਨ ਤੋਂ ਬੁਖ਼ਾਰ",
    symptom_cat: "ਲੱਛਣ ਦੀ ਸ਼੍ਰੇਣੀ",
    symptom_cat_opts: ["ਸਧਾਰਨ", "ਸਾਹ ਲੈਣ ਵਾਲੀ ਤਕਲੀਫ਼", "ਦਿਲ ਦੀ ਬਿਮਾਰੀ", "ਪੇਟ", "ਹੋਰ"],
    category_type: "ਕਿਸਮ",
    category_type_opts: ["ਮੁੱਖ", "ਦੋਹਰਾਏ ਗਏ", "ਦੀਰਘਕਾਲੀ", "ਹੋਰ"],
    symptoms: "ਲੱਛਣ",
    symptoms_ph: "ਉਦਾਹ: ਸਿਰ ਦਰਦ",
    duration: "ਅਵਧੀ",
    duration_opts: ["ਘੰਟੇ", "ਦਿਨ", "ਹਫ਼ਤੇ"],
    severity: "ਤੀਬਰਤਾ",
    severity_opts: ["ਹਲਕੀ", "ਦਰਮਿਆਨੀ", "ਤਿਖੀ"],
    health_history: "ਸਿਹਤ ਇਤਿਹਾਸ",
    diabetes: "ਸ਼ੂਗਰ",
    bp: "ਬੀ.ਪੀ.",
    tb: "ਟੀ.ਬੀ.",
    asthma: "ਦਮ",
    other: "ਹੋਰ",
    cur_meds: "ਮੌਜੂਦਾ ਦਵਾਈਆਂ",
    cur_meds_ph: "ਹਾਂ/ਨਹੀਂ ਜਾਂ ਨਾਮ ਲਿਖੋ",
    date: "ਤਾਰੀਖ",
    date_ph: "ਸਾਲ-ਮਹੀਨਾ-ਦਿਨ",
    time: "ਸਮਾਂ",
    time_ph: "ਘੰਟੇ:ਮਿੰਟ",
    hosp: "ਹਸਪਤਾਲ ਦੀ ਕਿਸਮ",
    select_hosp: "ਕਿਸਮ ਚੁਣੋ",
    private: "ਨਿੱਜੀ",
    govt: "ਸਰਕਾਰੀ",
    submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
  },
  hi: {
    form: "रोगी परामर्श प्रपत्र",
    reason: "मुलाकात का कारण",
    reason_ph: "उदा: 2 दिन से बुखार",
    symptom_cat: "लक्षण श्रेणी",
    symptom_cat_opts: ["सामान्य", "सांस संबंधी", "हृदय", "पाचन", "अन्य"],
    category_type: "प्रकार",
    category_type_opts: ["प्राथमिक", "पुनरावर्ती", "दीर्घकालिक", "अन्य"],
    symptoms: "लक्षण",
    symptoms_ph: "उदा: सिरदर्द",
    duration: "अवधि",
    duration_opts: ["घंटे", "दिन", "सप्ताह"],
    severity: "तीव्रता",
    severity_opts: ["माइल्ड", "मध्यम", "तीव्र"],
    health_history: "स्वास्थ्य इतिहास",
    diabetes: "मधुमेह",
    bp: "रक्तचाप",
    tb: "क्षय रोग",
    asthma: "अस्थमा",
    other: "अन्य",
    cur_meds: "वर्तमान दवाएं",
    cur_meds_ph: "हाँ/ना या नाम लिखें",
    date: "तारीख",
    date_ph: "साल-माह-दिन",
    time: "समय",
    time_ph: "घंटा:मिनट",
    hosp: "अस्पताल का प्रकार",
    select_hosp: "प्रकार चुनें",
    private: "निजी",
    govt: "सरकारी",
    submit: "सबमिट करें",
  },
  bn: {
    form: "রোগীর পরামর্শ ফর্ম",
    reason: "আসার কারণ",
    reason_ph: "উদা: ২ দিন ধরে জ্বর",
    symptom_cat: "লক্ষণ শ্রেণী",
    symptom_cat_opts: ["সাধারণ", "শ্বাসজনিত", "হার্ট", "পাচন", "অন্যান্য"],
    category_type: "প্রকার",
    category_type_opts: ["প্রাথমিক", "বারবার হওয়া", "দীর্ঘস্থায়ী", "অন্যান্য"],
    symptoms: "লক্ষণ",
    symptoms_ph: "উদা: মাথাব্যথা",
    duration: "সময়কাল",
    duration_opts: ["ঘণ্টা", "দিন", "সপ্তাহ"],
    severity: "তীব্রতা",
    severity_opts: ["হালকা", "মধ্যম", "তীব্র"],
    health_history: "স্বাস্থ্য ইতিহাস",
    diabetes: "ডায়াবেটিস",
    bp: "রক্তচাপ",
    tb: "ক্ষয়রোগ",
    asthma: "হাঁপানি",
    other: "অন্যান্য",
    cur_meds: "বর্তমান ওষুধ",
    cur_meds_ph: "হ্যাঁ/না বা নাম লিখুন",
    date: "তারিখ",
    date_ph: "বছর-মাস-দিন",
    time: "সময়",
    time_ph: "ঘণ্টা:মিনিট",
    hosp: "হাসপাতালের ধরণ",
    select_hosp: "ধরণ নির্বাচন করুন",
    private: "বেসরকারি",
    govt: "সরকারি",
    submit: "জমা দিন",
  },
  ta: {
    form: "நோயாளியின் ஆலோசனை படிவம்",
    reason: "பார்வை காரணம்",
    reason_ph: "உதா: 2 நாட்கள் காய்ச்சல்",
    symptom_cat: "குறிப்பு வகை",
    symptom_cat_opts: ["தொகுதி", "மூச்சுவர்க்கு", "இதயம்", "அஹாரம்", "மற்றவை"],
    category_type: "வகை",
    category_type_opts: ["முதன்மை", "மீண்டும்", "நோய்ப்பு", "மற்றவை"],
    symptoms: "குறிப்புகள்",
    symptoms_ph: "உதா: தலைவலி",
    duration: "நாட்கள்",
    duration_opts: ["மணி", "நாள்", "வாரம்"],
    severity: "கடுமை",
    severity_opts: ["மிதமான", "நெருக்கமான", "கடுமையான"],
    health_history: "ஆரோக்கிய வரலாறு",
    diabetes: "நீரிழிவு",
    bp: "இரத்த அழுத்தம்",
    tb: "பசிப்பரிதாபம்",
    asthma: "உடல் மூச்சுத்திணறல்",
    other: "மற்றவை",
    cur_meds: "தற்போதைய மருந்துகள்",
    cur_meds_ph: "ஆம்/இல்லை அல்லது பெயர்கள்",
    date: "தேதி",
    date_ph: "ஆண்டு-மாதம்-நாள்",
    time: "நேரம்",
    time_ph: "மணி:நிமிடம்",
    hosp: "மருத்துவமனை வகை",
    select_hosp: "வகையைத் தேர்ந்தெடு",
    private: "வர்த்தக",
    govt: "அரசு",
    submit: "சமர்ப்பி",
  }
};